# Generated by Django 3.2 on 2023-03-06 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotecategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotecategoryname', models.CharField(max_length=254)),
                ('quotecategory_friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Quote Categories',
            },
        ),
        migrations.CreateModel(
            name='Quotecategorydetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotecategorydetail', models.CharField(blank=True, max_length=254, null=True)),
                ('baseprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quotecategorydetail_friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('quotecategoryname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.quotecategory')),
            ],
            options={
                'verbose_name_plural': 'Quote Category Details',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(editable=False, max_length=32)),
                ('quotecategorydetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.quotecategorydetail')),
                ('quotecategoryname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.quotecategory')),
            ],
        ),
    ]
