# Generated by Django 3.2 on 2023-03-06 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quotecategorydetail',
            new_name='quote_category_detail',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quotecategoryname',
            new_name='quote_category_name',
        ),
        migrations.RenameField(
            model_name='quotecategory',
            old_name='quotecategory_friendly_name',
            new_name='quote_category_friendly_name',
        ),
        migrations.RenameField(
            model_name='quotecategory',
            old_name='quotecategoryname',
            new_name='quote_category_name',
        ),
        migrations.RenameField(
            model_name='quotecategorydetail',
            old_name='quotecategorydetail',
            new_name='quote_category_detail',
        ),
        migrations.RenameField(
            model_name='quotecategorydetail',
            old_name='quotecategorydetail_friendly_name',
            new_name='quote_category_detail_friendly_name',
        ),
        migrations.RenameField(
            model_name='quotecategorydetail',
            old_name='quotecategoryname',
            new_name='quote_category_name',
        ),
        migrations.AddField(
            model_name='quote',
            name='baseprice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoteprice', to='quotes.quotecategorydetail'),
        ),
    ]
