# Generated by Django 3.2 on 2023-03-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20230306_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotecategorydetail',
            old_name='baseprice',
            new_name='base_price_quote',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='baseprice',
        ),
        migrations.AddField(
            model_name='quote',
            name='base_price_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basepricequote', to='quotes.quotecategorydetail'),
        ),
    ]
