# Generated by Django 3.2 on 2023-03-06 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20230306_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='base_price_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_base_price_quote', to='quotes.quotecategorydetail'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_category_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_quote_category_detail', to='quotes.quotecategorydetail'),
        ),
    ]
