# Generated by Django 3.2 on 2023-03-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20230306_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='base_price_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_basepricequote', to='quotes.quotecategorydetail'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_category_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_quotecategorydetail', to='quotes.quotecategorydetail'),
        ),
    ]
