# Generated by Django 3.2 on 2023-03-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20230306_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
