# Generated by Django 3.2 on 2023-03-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_delete_quote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotecategorydetail',
            new_name='Quote',
        ),
    ]
