# Generated by Django 3.2 on 2023-03-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_rename_quotecategorydetail_quote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quotecategory',
            options={},
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_category_name',
            new_name='quote_category',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='base_price_quote',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quote_category_detail_friendly_name',
        ),
        migrations.RemoveField(
            model_name='quotecategory',
            name='quote_category_name',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(default=1234, editable=False, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='quote_category',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='QuoteCategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_category_detail', models.CharField(blank=True, max_length=254, null=True)),
                ('quote_category_detail_friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('quote_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quotecategory')),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_category_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.quotecategorydetail'),
        ),
    ]
