# Generated by Django 3.2 on 2023-03-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_auto_20230307_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
