# Generated by Django 3.2 on 2023-03-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_rename_quote_category_detail_quotecategorydetail_quote_category_detail_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotecategory',
            old_name='quote_category',
            new_name='quote_category_name',
        ),
    ]
