# Generated by Django 3.2 on 2023-03-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_quote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
