# Generated by Django 3.2 on 2023-03-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_quote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotecategory',
            options={'verbose_name_plural': 'Quote Categories'},
        ),
        migrations.AlterModelOptions(
            name='quotecategorydetail',
            options={'verbose_name_plural': 'Quote Category Detail'},
        ),
    ]
