# Generated by Django 3.2 on 2023-03-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_auto_20230308_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote_category',
            new_name='quotecategory',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_category_detail_name',
            new_name='quotecategorydetail',
        ),
        migrations.RenameField(
            model_name='quotecategory',
            old_name='quote_category_friendly_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quotecategorydetail',
            old_name='quote_category_detail_friendly_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quotecategorydetail',
            old_name='quote_category',
            new_name='quotecategory',
        ),
        migrations.RemoveField(
            model_name='quotecategory',
            name='quote_category_name',
        ),
        migrations.RemoveField(
            model_name='quotecategorydetail',
            name='quote_category_detail_name',
        ),
    ]
