# Generated by Django 3.2 on 2023-03-09 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0018_quotecategorydetail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseprice', to='quotes.quotecategorydetail'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quotecategorydetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailname', to='quotes.quotecategorydetail'),
        ),
    ]
