# Generated by Django 3.2 on 2023-03-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0019_auto_20230309_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='price',
        ),
    ]
