# Generated by Django 3.2 on 2023-03-09 18:45

from django.db import migrations, models
import django.utils.timezone
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0022_remove_quotecategorydetail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotecategorydetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('00.0000'), max_digits=6),
            preserve_default=False,
        ),
    ]
