# Generated by Django 3.2 on 2023-03-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0023_auto_20230309_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotecategorydetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
