# Generated by Django 3.2 on 2023-03-09 20:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0025_auto_20230309_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotecategorydetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
