# Generated by Django 3.2 on 2023-03-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0026_quotecategorydetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotecategorydetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
