# Generated by Django 3.2 on 2023-03-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0027_alter_quotecategorydetail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pickup',
            field=models.CharField(choices=[('Y', 'Yes, I need you to pickup my furniture'), ('N', 'No, I will drop it to your shop')], default='N', max_length=3),
        ),
    ]
