# Generated by Django 3.2 on 2023-03-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0028_quote_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pickup_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
