# Generated by Django 3.2 on 2023-03-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0029_quote_pickup_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
