# Generated by Django 3.2 on 2023-03-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0030_quote_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
