# Generated by Django 3.2 on 2023-03-19 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('name', 'chairs'), ('name', 'sofas'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
