# Generated by Django 3.2 on 2023-04-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
