# Generated by Django 3.2 on 2023-04-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_review_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
